"""Dynamic loading-state quotes — generated by Gemini, not hardcoded copy."""

from __future__ import annotations

import logging
import time
from typing import TYPE_CHECKING

from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field

from core.config import DEFAULT_SECTOR, sector_slugify

if TYPE_CHECKING:
    from langchain_google_genai import ChatGoogleGenerativeAI

logger = logging.getLogger(__name__)

_CACHE_TTL_SEC = 900
_cache: dict[tuple[str, str, int], tuple[float, list[str]]] = {}

LOADING_HINTS_SYSTEM = """You write short, original one-liner quotes about customer experience, guest satisfaction, listening to feedback, and hospitality or service excellence.

Rules:
- Match the requested language exactly.
- Each quote is one sentence, max ~120 characters, warm and professional (not cheesy marketing slogans).
- Do NOT copy famous authors or brand taglines verbatim — invent fresh wording each time.
- Do NOT mention product names (Pivony, dashboards, AI, tools).
- Quotes should feel relevant to someone waiting for guest-voice analytics insights."""


class LoadingHintsResult(BaseModel):
    quotes: list[str] = Field(
        description="Short CX-themed quotes for a loading state.",
        min_length=1,
        max_length=5,
    )


def _lang_label(lang: str) -> str:
    code = (lang or "tr").strip().lower()[:2]
    return "Turkish" if code == "tr" else "English"


def generate_loading_hints(
    *,
    lang: str = "tr",
    sector_slug: str = DEFAULT_SECTOR,
    count: int = 3,
    llm: ChatGoogleGenerativeAI,
) -> list[str]:
    """Return `count` fresh CX quotes (cached briefly per lang/sector/count)."""
    slug = sector_slugify(sector_slug or DEFAULT_SECTOR)
    n = min(max(1, int(count)), 5)
    cache_key = (slug, (lang or "tr").lower()[:2], n)
    now = time.time()
    cached = _cache.get(cache_key)
    if cached and now - cached[0] < _CACHE_TTL_SEC:
        return list(cached[1])

    prompt = (
        f"Language: {_lang_label(lang)}\n"
        f"Industry context: {slug}\n"
        f"Generate exactly {n} distinct quotes."
    )
    try:
        structured = llm.with_structured_output(LoadingHintsResult, method="json_schema")
        result = structured.invoke(
            [
                SystemMessage(content=LOADING_HINTS_SYSTEM),
                HumanMessage(content=prompt),
            ]
        )
        if not isinstance(result, LoadingHintsResult):
            result = LoadingHintsResult.model_validate(result)
        quotes = [q.strip() for q in result.quotes if q and str(q).strip()]
        quotes = quotes[:n]
        if quotes:
            _cache[cache_key] = (now, quotes)
            return quotes
    except Exception as exc:
        logger.warning("loading hints generation failed: %s", exc)
    return []
